/**
 * Satellite classification rules.
 *
 * Categories:
 *   civilian  — Commercial telecom, internet constellations, navigation (GPS/GLONASS/BeiDou/Galileo)
 *   research  — Scientific, weather, Earth observation, space stations
 *   military  — Defense/intelligence (NRO, missile warning, milcom)
 *
 * Keywords are matched against the uppercase TLE satellite name.
 * Order matters: first match wins.
 */
export const SATELLITE_CLASSIFICATION = {
  keywords: {
    civilian: [
      'STARLINK',
      'ONEWEB',
      'IRIDIUM',
      'KUIPER',
      'INTELSAT',
      'SES',
      'TELESAT',
      'GLOBALSTAR',
      'ORBCOMM',
      // Navigation constellations (dual-use, but primarily civilian utility)
      'GPS',
      'GLONASS',
      'BEIDOU',
      'GALILEO',
      'NAVSTAR',
    ],
    research: [
      'ISS',
      'ZARYA',
      'HUBBLE',
      'NOAA',
      'AQUA',
      'TERRA',
      'GOES',
      'LANDSAT',
      'SENTINEL',
      'ICESAT',
      'ENVISAT',
      'FENGYUN',
      'METOP',
      'SUOMI',
      'CALIPSO',
      'CLOUDSAT',
      'GRACE',
      'JASON',
      'TOPEX',
      'QUICKSCAT',
      'WINDSAT',
      'ERS',
      'METEOR',
      'CBERS',
      'RESURS',
      'ALOS',
      'SPOT',
      'SARAL',
      'SMAP',
      'OCO',
      'SWOT',
      'PACE',
      'COSMIC',
      'CHAMP',
      'GOCE',
      'CRYOSAT',
      'AEOLUS',
      'TIANGONG',
      'SHENZHOU',
      'TIANZHOU',
      'PROGRESS',
      'SOYUZ',
      'CREW DRAGON',
      'CYGNUS',
      'HTV',
    ],
    military: [
      'NROL',
      'NOSS',
      'MUOS',
      'AEHF',
      'SBIRS',
      'DSCS',
      'WGS',
      'MILSTAR',
      'DSP',
      'DMSP',
      'SDS',
      'LACROSSE',
      'MISTY',
      'ORION',
      'TRUMPET',
      'MENTOR',
      'INTRUDER',
      'PROWLER',
      'NEMESIS',
      'TOPAZ',
      'PERSONA',
      'KONDOR',
      'PARUS',
      'STRELA',
      'RODNIK',
      'LUCH',
      'KOSMOS',
    ],
  },
  systems: {
    // Civilian
    STARLINK: 'SpaceX Starlink',
    ONEWEB: 'OneWeb',
    IRIDIUM: 'Iridium',
    KUIPER: 'Amazon Kuiper',
    INTELSAT: 'Intelsat',
    SES: 'SES',
    TELESAT: 'Telesat',
    GLOBALSTAR: 'Globalstar',
    ORBCOMM: 'Orbcomm',
    GPS: 'GPS Navigation',
    GLONASS: 'GLONASS Navigation',
    BEIDOU: 'BeiDou Navigation',
    GALILEO: 'Galileo Navigation',
    NAVSTAR: 'GPS Navigation',

    // Research
    ISS: 'Int\'l Space Station',
    ZARYA: 'Int\'l Space Station',
    HUBBLE: 'Space Telescope',
    NOAA: 'NOAA Weather',
    AQUA: 'NASA EOS',
    TERRA: 'NASA EOS',
    GOES: 'NOAA Weather',
    LANDSAT: 'USGS/NASA',
    SENTINEL: 'ESA Copernicus',
    ICESAT: 'NASA',
    ENVISAT: 'ESA',
    FENGYUN: 'CMA Weather',
    METOP: 'EUMETSAT',
    SUOMI: 'NASA/NOAA',
    CALIPSO: 'NASA/CNES',
    CLOUDSAT: 'NASA/CSA',
    GRACE: 'NASA/DLR',
    JASON: 'NASA/CNES',
    TOPEX: 'NASA/CNES',
    QUICKSCAT: 'NASA',
    WINDSAT: 'US Navy/NASA',
    ERS: 'ESA',
    METEOR: 'Roshydromet',
    CBERS: 'INPE/CNSA',
    RESURS: 'Roscosmos',
    ALOS: 'JAXA',
    SPOT: 'CNES',
    TIANGONG: 'CMSA',
    SHENZHOU: 'CMSA',

    // Military
    NROL: 'NRO',
    NOSS: 'NRO SIGINT',
    MUOS: 'US Navy SATCOM',
    AEHF: 'US Space Force',
    SBIRS: 'Missile Warning',
    DSCS: 'US DoD SATCOM',
    WGS: 'US DoD SATCOM',
    MILSTAR: 'US Space Force',
    DSP: 'Missile Warning',
    DMSP: 'DoD Weather',
    SDS: 'NRO Relay',
    LACROSSE: 'NRO Radar',
    PERSONA: 'Russian MoD',
    KONDOR: 'Russian MoD',
    KOSMOS: 'Russian MoD',
    PARUS: 'Russian Navy',
    STRELA: 'Russian MoD',
    RODNIK: 'Russian Navy',
    TOPAZ: 'Russian MoD',
    LUCH: 'Russian MoD',
  },
  fallbackRegex: {
    research:
      /\b(ISS|ZARYA|HUBBLE|NOAA|AQUA|TERRA|METEOR|GOES|WINDSAT|QUICKSCAT|ERS|ENVISAT|SENTINEL|LANDSAT|ICESAT|TIANGONG|SHENZHOU)\b/i,
    militaryUsa: /\bUSA\s+\d+\b/i,
    military:
      /\b(NROL|NOSS|MUOS|AEHF|SBIRS|DSCS|WGS|MILSTAR|DSP|DMSP|SDS|LACROSSE|KOSMOS)\b/i,
    numericNorad: /^\d+$|NORAD\s*\d+/i,
  },
} as const;
