import type { DataPointGroup, SourceDefinition } from '@/features/sources/types';

export const SOURCE_DEFINITIONS: SourceDefinition[] = [
  {
    id: 'air.adsb',
    label: 'ADSB.lol Aircraft',
    domain: 'air',
    auth: { type: 'none', requiresKey: false },
    coverage: 'Global community ADS-B aircraft positions near the current viewport.',
    cadenceMs: 12_000,
    attribution: 'ADSB.lol, ODbL 1.0',
    termsUrl: 'https://www.adsb.lol/docs/open-data/api/',
    timeoutMs: 6_000,
    concurrency: 1,
    capabilities: ['snapshot'],
    defaultEnabled: true,
    color: '#5AC8FA',
    usage: 'Public no-key endpoint; keep requests viewport-bound.',
  },
  {
    id: 'space.celestrak',
    label: 'CelesTrak Orbital Objects',
    domain: 'space',
    auth: { type: 'none', requiresKey: false },
    coverage: 'Public GP orbital elements for active Earth-orbiting objects.',
    cadenceMs: 7_200_000,
    attribution: 'CelesTrak',
    termsUrl: 'https://celestrak.org/NORAD/documentation/gp-data-formats.php',
    timeoutMs: 9_000,
    concurrency: 1,
    capabilities: ['snapshot'],
    defaultEnabled: true,
    color: '#A78BFA',
    usage: 'Use current GP query format; avoid repeated broad downloads.',
  },
  {
    id: 'events.usgs-earthquakes',
    label: 'USGS Earthquakes',
    domain: 'earth',
    auth: { type: 'none', requiresKey: false },
    coverage: 'Recent global earthquakes from USGS GeoJSON feeds.',
    cadenceMs: 60_000,
    attribution: 'U.S. Geological Survey',
    termsUrl: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php',
    timeoutMs: 6_000,
    concurrency: 1,
    capabilities: ['snapshot'],
    defaultEnabled: true,
    color: '#FF9F43',
    usage: 'Use realtime GeoJSON feeds for display.',
  },
  {
    id: 'events.nasa-eonet',
    label: 'NASA EONET Natural Events',
    domain: 'earth',
    auth: { type: 'none', requiresKey: false },
    coverage: 'Open natural events including wildfires, storms, volcanoes, and dust.',
    cadenceMs: 300_000,
    attribution: 'NASA EONET',
    termsUrl: 'https://eonet.gsfc.nasa.gov/docs/v3',
    timeoutMs: 7_000,
    concurrency: 1,
    capabilities: ['snapshot'],
    defaultEnabled: true,
    color: '#FBBF24',
    usage: 'Open API; preserve event source links.',
  },
  {
    id: 'events.gdacs',
    label: 'GDACS Disaster Alerts',
    domain: 'disaster',
    auth: { type: 'none', requiresKey: false },
    coverage: 'Recent global disaster alerts and humanitarian early-warning events.',
    cadenceMs: 300_000,
    attribution: 'Global Disaster Alert and Coordination System, GDACS',
    termsUrl: 'https://www.gdacs.org/Documents/2025/GDACS_API_quickstart_v1.pdf',
    timeoutMs: 8_000,
    concurrency: 1,
    capabilities: ['snapshot'],
    defaultEnabled: true,
    color: '#FF6B6B',
    usage: 'Limit result windows and acknowledge GDACS.',
  },
  {
    id: 'weather.open-meteo',
    label: 'Open-Meteo Weather',
    domain: 'weather',
    auth: { type: 'none', requiresKey: false, notes: 'Public-use endpoint with attribution requirements.' },
    coverage: 'Current weather model values for the viewport center.',
    cadenceMs: 300_000,
    attribution: 'Open-Meteo, national weather services',
    termsUrl: 'https://github.com/open-meteo/open-meteo',
    timeoutMs: 6_000,
    concurrency: 1,
    capabilities: ['indicator', 'snapshot'],
    defaultEnabled: true,
    color: '#48BFE3',
    usage: 'Free for non-commercial use; include attribution.',
  },
  {
    id: 'air-quality.open-meteo',
    label: 'Open-Meteo Air Quality',
    domain: 'weather',
    auth: { type: 'none', requiresKey: false, notes: 'Public-use endpoint with attribution requirements.' },
    coverage: 'Current air quality indicators for the viewport center.',
    cadenceMs: 300_000,
    attribution: 'Open-Meteo and CAMS providers',
    termsUrl: 'https://open-meteo.com/en/docs/air-quality-api',
    timeoutMs: 6_000,
    concurrency: 1,
    capabilities: ['indicator', 'snapshot'],
    defaultEnabled: true,
    color: '#34D399',
    usage: 'Free public endpoint with attribution requirements.',
  },
  {
    id: 'marine.open-meteo',
    label: 'Open-Meteo Marine',
    domain: 'weather',
    auth: { type: 'none', requiresKey: false, notes: 'Public-use endpoint with attribution requirements.' },
    coverage: 'Marine wave and sea-state indicators near the viewport center.',
    cadenceMs: 300_000,
    attribution: 'Open-Meteo Marine API',
    termsUrl: 'https://open-meteo.com/en/docs/marine-weather-api',
    timeoutMs: 6_000,
    concurrency: 1,
    capabilities: ['indicator', 'snapshot'],
    defaultEnabled: false,
    color: '#2DD4BF',
    usage: 'Query only for current viewport center.',
  },
  {
    id: 'flood.open-meteo',
    label: 'Open-Meteo Flood',
    domain: 'disaster',
    auth: { type: 'none', requiresKey: false, notes: 'Public-use endpoint with attribution requirements.' },
    coverage: 'Flood-related river discharge indicators where available.',
    cadenceMs: 600_000,
    attribution: 'Open-Meteo Flood API',
    termsUrl: 'https://open-meteo.com/en/docs/flood-api',
    timeoutMs: 6_000,
    concurrency: 1,
    capabilities: ['indicator', 'snapshot'],
    defaultEnabled: false,
    color: '#60A5FA',
    usage: 'Handle unsupported regions gracefully.',
  },
  {
    id: 'space-weather.noaa-swpc',
    label: 'NOAA SWPC Space Weather',
    domain: 'space-weather',
    auth: { type: 'none', requiresKey: false },
    coverage: 'Planetary K-index and solar wind indicators.',
    cadenceMs: 120_000,
    attribution: 'NOAA Space Weather Prediction Center',
    termsUrl: 'https://services.swpc.noaa.gov/',
    timeoutMs: 6_000,
    concurrency: 1,
    capabilities: ['indicator', 'snapshot'],
    defaultEnabled: true,
    color: '#F472B6',
    usage: 'Use JSON products directly and keep request cadence conservative.',
  },
  {
    id: 'media.gdelt',
    label: 'GDELT Media Signals',
    domain: 'media',
    auth: { type: 'none', requiresKey: false },
    coverage: 'Caveated media-derived signals for conflict, protests, and disruption.',
    cadenceMs: 300_000,
    attribution: 'GDELT Project',
    termsUrl: 'https://gdelt.github.io/',
    timeoutMs: 7_000,
    concurrency: 1,
    capabilities: ['snapshot'],
    defaultEnabled: false,
    color: '#EF4444',
    usage: 'Media signal only; do not present as authoritative conflict ground truth.',
  },
  {
    id: 'imagery.earth-search',
    label: 'Earth Search Imagery',
    domain: 'imagery',
    auth: { type: 'none', requiresKey: false },
    coverage: 'Newest Sentinel/Landsat scene metadata for an inspected location.',
    cadenceMs: 300_000,
    attribution: 'Element84 Earth Search and AWS Open Data',
    termsUrl: 'https://element84.com/earth-search',
    timeoutMs: 9_000,
    concurrency: 1,
    capabilities: ['imagery-inspection'],
    defaultEnabled: true,
    color: '#E0E7FF',
    usage: 'Use only for explicit inspect requests.',
  },
  {
    id: 'imagery.gibs',
    label: 'NASA GIBS Imagery',
    domain: 'imagery',
    auth: { type: 'none', requiresKey: false },
    coverage: 'NASA time-aware browse imagery fallback for inspected locations.',
    cadenceMs: 300_000,
    attribution: 'NASA Global Imagery Browse Services',
    termsUrl: 'https://nasa-gibs.github.io/gibs-api-docs/access-basics/',
    timeoutMs: 8_000,
    concurrency: 1,
    capabilities: ['imagery-inspection', 'raster-overlay'],
    defaultEnabled: true,
    color: '#CBD5E1',
    usage: 'Use standards-based WMS/WMTS URLs with date metadata.',
  },
];

export const SOURCE_DEFINITION_BY_ID = new Map(
  SOURCE_DEFINITIONS.map((source) => [source.id, source]),
);

export const DEFAULT_SOURCE_IDS = SOURCE_DEFINITIONS
  .filter((source) => source.defaultEnabled)
  .map((source) => source.id);

export const DATA_POINT_GROUPS: DataPointGroup[] = [
  {
    id: 'traffic',
    label: 'Traffic',
    sources: [
      dataPoint('air.adsb', 'Aircraft', 'Live aircraft positions from ADSB.lol.'),
      dataPoint('space.celestrak', 'Orbital Objects', 'Live propagated orbital objects from CelesTrak GP data.'),
    ],
  },
  {
    id: 'earth-events',
    label: 'Earth Events',
    sources: [
      dataPoint('events.usgs-earthquakes', 'Earthquakes', 'Recent USGS earthquake feed.'),
      dataPoint('events.nasa-eonet', 'Natural Events', 'NASA EONET open natural events.'),
      dataPoint('events.gdacs', 'Disaster Alerts', 'GDACS early-warning disaster alerts.'),
    ],
  },
  {
    id: 'environment',
    label: 'Environment',
    sources: [
      dataPoint('weather.open-meteo', 'Weather', 'Current weather for the map center.'),
      dataPoint('air-quality.open-meteo', 'Air Quality', 'Current air-quality indicators for the map center.'),
      dataPoint('marine.open-meteo', 'Marine', 'Sea-state indicators for coastal and ocean contexts.'),
      dataPoint('flood.open-meteo', 'Flood', 'River-discharge flood indicators where available.'),
      dataPoint('space-weather.noaa-swpc', 'Space Weather', 'NOAA SWPC solar and geomagnetic indicators.'),
    ],
  },
  {
    id: 'media-and-imagery',
    label: 'Media & Imagery',
    sources: [
      dataPoint('media.gdelt', 'Conflict Signals', 'Caveated media-derived conflict and disruption signals.'),
      dataPoint('imagery.earth-search', 'Earth Search Inspect', 'Newest Sentinel/Landsat scene metadata.'),
      dataPoint('imagery.gibs', 'NASA GIBS Inspect', 'NASA browse imagery fallback for inspected locations.'),
    ],
  },
];

function dataPoint(sourceId: string, label: string, description: string) {
  const source = SOURCE_DEFINITION_BY_ID.get(sourceId);
  if (!source) {
    throw new Error(`Unknown source id: ${sourceId}`);
  }

  return {
    sourceId,
    label,
    description,
    color: source.color,
  };
}
